services:
  job:
    image: postgres:latest
    environment:
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: superadmin
      POSTGRES_DB: job
    ports:
      - "5432:5432"
    volumes:
      - job_bd_data:/var/lib/postgresql/data
volumes:
  job_bd_data:
