services:
  olipm:
    image: postgres:latest
    environment:
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: superadmin
      POSTGRES_DB: olimp
    ports:
      - "5432:5432"
    volumes:
      - olimp_bd_data:/var/lib/postgresql/data
volumes:
  olimp_bd_data:
